DROP TABLE IF EXISTS assignee_groups CASCADE;

DROP TABLE IF EXISTS statuses CASCADE;

DROP TABLE IF EXISTS statuses_localized CASCADE;

DROP TABLE IF EXISTS persons CASCADE;

DROP TABLE IF EXISTS tasks CASCADE;